FROM jenkins/jenkins
 
USER root
RUN apt-get -y update && apt-get install -y maven
 //Se realiza la instalación d elos archivos por medio de los comandos  los cuales actualizan los paques y la instalación correspondiente//
USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
