FROM jenkins/jenkins
USER root
RUN apt-get -y update && apt-get install -y maven
 //Se ejecuta el comando apt-get -y par actualizar los paquetes e instalar la opción de maven//
USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
